[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"

[general]
import = [
"~/.config/alacritty/themes/alacritty-theme/themes/dark_plus.toml"]
live_config_reload = true

[scrolling]
history = 10000
multiplier = 3

[window]
padding = { x = 2, y = 2 }
decorations     = "none"
dynamic_padding = false
dynamic_title   = true
opacity         = 1.0
startup_mode    = "Maximized"
title           = "Alacritty"

[colors.primary]
background = '#181616'
foreground = '#c5c9c5'

[colors.normal]
black   = '#0d0c0c'
red     = '#c4746e'
green   = '#8a9a7b'
yellow  = '#c4b28a'
blue    = '#8ba4b0'
magenta = '#a292a3'
cyan    = '#8ea4a2'
white   = '#C8C093'

[colors.bright]
black   = '#a6a69c'
red     = '#E46876'
green   = '#87a987'
yellow  = '#E6C384'
blue    = '#7FB4CA'
magenta = '#938AA9'
cyan    = '#7AA89F'
white   = '#c5c9c5'

[colors.selection]
background = '#2D4F67'
foreground = '#C8C093'

[[colors.indexed_colors]]
index = 16
color = '#b6927b'

[[colors.indexed_colors]]
index = 17
color = '#b98d7b'

[font]
builtin_box_drawing = false
size                = 7.5 # 10 on gnome, 7.5 on i3

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style  = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style  = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style  = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style  = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[cursor]
style = { shape = "Block" }
unfocused_hollow = true

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "Paste"
key    = "V"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key    = "C"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key    = "N"
mods   = "Control|Alt"

# [[keyboard.bindings]]
# action = "Quit"
# key    = "D"
# mods   = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key    = "F11"

[[keyboard.bindings]]
action = "ScrollToTop"
key    = "Home"
mods   = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key    = "End"
mods   = "Control"

