# Preload the image into memory
preload = ~/.config/hypr/wallpaper.jpg

# Set the wallpaper for all monitors (indicated by the empty space before the comma)
wallpaper = ,~/.config/hypr/wallpaper.jpg

# Disable the "splash" (Hyprland logo/text) if you want a clean look
splash = false
